accounts/urls.py
from django.urls import path, include

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

calendarapp/urls.py
from django.urls import path

from . import views
app_name = "calendarapp"


urlpatterns = [
    path("calender/", views.CalendarViewNew.as_view(), name="calendar"),
    path("report/", views.ReportView, name="report"),
    path("calenders/", views.CalendarView.as_view(), name="calendars"),
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('next_week/<int:event_id>/', views.next_week, name='next_week'),
    path('next_day/<int:event_id>/', views.next_day, name='next_day'),
    path("event/new/", views.create_event, name="event_new"),
    path("event/edit/<int:pk>/", views.EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        views.EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        views.RunningEventsListView.as_view(),
        name="running_events",
    ),
]

eventcalendar/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("calendarapp.urls")),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="fa-ir">
    {% load static %}
    <head>
        <meta name="description" content="Event Dashboard" />
        <meta property="og:description" content="Event Dashboard" />
        <title>{% block title %}{% endblock title  %}</title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Main CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
        <!-- Font-icon css-->
        <link rel="stylesheet" href="{% static 'css/accounts.css' %}" />
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
        {% block extracss %}
        {% endblock extracss %}
    </head>
    <body class="app sidebar-mini" dir="rtl">
        <!-- Navbar-->
        <header class="app-header">
            <a class="app-header__logo" href="#" style="font-family: vazir">تقویم دانشجویی</a>
            <!-- Sidebar toggle button-->
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
            <!-- Navbar Right Menu-->
            <ul class="app-nav">
                <li class="app-search">
                    <input class="app-search__input" type="search" placeholder="Search" />
                    <button class="app-search__button"><i class="fa fa-search"></i></button>
                </li>
                <!--Notification Menu-->
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Show notifications"><i class="fa fa-bell-o fa-lg"></i></a>
                    <ul class="app-notification dropdown-menu dropdown-menu-right">
                        <li class="app-notification__title" style="font-family: vazir">شما ۴ تا پیام خوانده نشده دارید.</li>
                        <div class="app-notification__content">
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <p class="app-notification__message" style="font-family: vazir">زهرا یک ایمیل برای شما ارسال کرد</p>
                                        <p class="app-notification__meta" style="font-family: vazir">۲ دقیقه پیش</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <p class="app-notification__message" style="font-family: vazir">سرور ایمیل کار نمیکند</p>
                                        <p class="app-notification__meta" style="font-family: vazir">۵ دقیقه پیش</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <p class="app-notification__message" style="font-family: vazir">کامل شد</p>
                                        <p class="app-notification__meta">۲ روز پیش</p>
                                    </div>
                                </a>
                            </li>
                            <div class="app-notification__content">
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <p class="app-notification__message">زهرا یک ایمیل برای شما ارسال کرد</p>
                                            <p class="app-notification__meta" style="font-family: vazir">۲ دقیقه پیش</p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <p class="app-notification__message" style="font-family: vazir">سرور ایمیل کار نمیکند</p>
                                            <p class="app-notification__meta" style="font-family: vazir">۵ دقیقه پیش</p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <p class="app-notification__message" style="font-family: vazir">تکمیل شد</p>
                                            <p class="app-notification__meta" style="font-family: vazir" >۲ روز پیش</p>
                                        </div>
                                    </a>
                                </li>
                            </div>
                        </div>
                        <li class="app-notification__footer" style="font-family: vazir"><a href="#" >دیدن تمام نوتیفیکیشن ها.</a></li>
                    </ul>
                </li>
                <!-- User Menu-->
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
                    <ul class="dropdown-menu settings-menu dropdown-menu-right">
                        <li>
                            <a class="dropdown-item" href="#" style="font-family: vazir"><i class="fa fa-cog fa-lg"></i>تنظیمات</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#" style="font-family: vazir"><i class="fa fa-user fa-lg"></i>پروفایل</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'accounts:signout' %}" style="font-family: vazir"><i class="fa fa-sign-out fa-lg"></i> خارج شدن</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </header>
        <!-- Sidebar menu-->
        <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        <aside class="app-sidebar">
            <div class="app-sidebar__user">
                <img class="app-sidebar__user-avatar" src="https://cdn1.iconfinder.com/data/icons/shopping-ecommerce-hexagonal-mix-set-2/64/53-1024.png" alt="User Image" height="50px" width="50px"/>
                <div>
                    <p class="app-sidebar__user-name" style="font-family: vazir">پارسا</p>
                    <p class="app-sidebar__user-designation" style="font-family: vazir">مهندس نرم‌افزار</p>
                </div>
            </div>
            <ul class="app-menu">
                <li>
                    <a class="app-menu__item active" href="{% url 'dashboard' %}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label" style="font-family: vazir">داشبورد</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'calendarapp:calendar' %}"><i class="app-menu__icon fa fa-calendar"></i><span class="app-menu__label" style="font-family: vazir">تقویم هفتگی</span></a>
                </li>
                <li class="treeview">
                    <a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label" style="font-family: vazir">رویدادها</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                    <ul class="treeview-menu">
                        <li>
                            <a  style="font-family: vazir" class="treeview-item" href="{% url 'calendarapp:running_events' %}"><i class="icon fa fa-circle-o" ></i> در حال اجرا</a>
                        </li>
                        <li>
                            <a style="font-family: vazir" class="treeview-item" href="{% url 'calendarapp:running_events' %}"><i class="icon fa fa-circle-o"></i> به زودی</a>
                        </li>
                        <li>
                            <a style="font-family: vazir" class="treeview-item" href="{% url 'calendarapp:all_events' %}"><i class="icon fa fa-circle-o" style="font-family: vazir"></i> همه </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a style="font-family: vazir" class="app-menu__item" href="#"><i class="app-menu__icon fa fa-file-code-o"></i><span class="app-menu__label">مقالات</span></a>
                </li>
                <li>
                    <a style="font-family: vazir" class="app-menu__item" href="{% url 'calendarapp:report' %}"><i class="app-menu__icon fa fa-file-code-o"></i><span class="app-menu__label">گزارش</span></a>
                </li>
            </ul>
        </aside>
        <main class="app-content">
            <div class="app-title">
                {% block breadcrumb %}
                {% endblock breadcrumb %}
            </div>
            {% block content %}
            {% endblock content %}
        </main>
        <!-- Essential javascripts for application to work-->
        {% include 'base/js.html' %}
        {% block extrascripts %}
        {% endblock extrascripts %}
    </body>
</html>

templates/base/js.html
{% load static %}
<script src="{% static 'js/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- The javascript plugin to display page loading on top-->
<script src="{% static 'js/plugins/pace.min.js'%}"></script>